// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNasBllW-QW5_nEjUtPvkpsylzTJkgAiQ',
    appId: '1:264419079364:web:81f2fecd6b7fd2b6970591',
    messagingSenderId: '264419079364',
    projectId: 'digital-bank-bankr-123',
    authDomain: 'digital-bank-bankr-123.firebaseapp.com',
    storageBucket: 'digital-bank-bankr-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhEnP_AIeYRUlJIVxjW7oHrlKZBRmKHpc',
    appId: '1:264419079364:android:f802c86cb489fc56970591',
    messagingSenderId: '264419079364',
    projectId: 'digital-bank-bankr-123',
    storageBucket: 'digital-bank-bankr-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_i3gHl1KW6Mr6FFtSnctSj_go-PU0epc',
    appId: '1:264419079364:ios:f99be7a092f384c3970591',
    messagingSenderId: '264419079364',
    projectId: 'digital-bank-bankr-123',
    storageBucket: 'digital-bank-bankr-123.firebasestorage.app',
    iosBundleId: 'com.example.digitalBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_i3gHl1KW6Mr6FFtSnctSj_go-PU0epc',
    appId: '1:264419079364:ios:f99be7a092f384c3970591',
    messagingSenderId: '264419079364',
    projectId: 'digital-bank-bankr-123',
    storageBucket: 'digital-bank-bankr-123.firebasestorage.app',
    iosBundleId: 'com.example.digitalBankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNasBllW-QW5_nEjUtPvkpsylzTJkgAiQ',
    appId: '1:264419079364:web:05e056215e9c84fb970591',
    messagingSenderId: '264419079364',
    projectId: 'digital-bank-bankr-123',
    authDomain: 'digital-bank-bankr-123.firebaseapp.com',
    storageBucket: 'digital-bank-bankr-123.firebasestorage.app',
  );
}
